apiVersion: v1
kind: Pod
metadata:
  name: mypod-{ID} # Try to make this dynamically generated (random)
  namespace: howest-github-actions # Enter your namespace here
  labels:
    name: mypod
spec:
  containers:
  - name: mypod
    image: rancher/hello-world
