apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: howest-github-actions
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30005
  type: NodePort  # Use LoadBalancer or NodePort if exposing externally