name: docker-image-ghcr

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{vars.GHCR_USERNAME}}/hello-world-nginx
  IMAGE_TAG: v1

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ IMAGE_NAME }}:${{ IMAGE_TAG }}  # it will be lowercased internally
          github_token: ${{ secrets.PAT_TOKEN }}
