name: kubernetes-pod

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - "**"


jobs:
  create_pod:
    runs-on: self-hosted

    steps:
      - name: look at the github repo
        uses: actions/checkout@v2

      - name: print current working directory
        shell: powershell
        run: |
            pwd
            ls

      - name: Set up kubeconfig
        shell: powershell
        run: |
            $kubeconfigPath = "$Env:USERPROFILE\kubeconfig"
            Set-Content -Path $kubeconfigPath -Value '${{ secrets.KUBECONFIG_DATA }}'

      - name: Test cluster access
        shell: powershell
        run: |
            $kubeconfigPath = "$Env:USERPROFILE\kubeconfig"
            kubectl --kubeconfig=$kubeconfigPath get nodes

      - name: Create a kubernetes pod
        shell: powershell
        run: kubectl --kubeconfig=$kubeconfigPath apply -f ./howest_github_actions/kubernetes/resource.yaml
          


