name: kubernetes-pod

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - "**"


jobs:
  create_pod:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Create a kubernetes pod
        run: kubectl apply -f ./kubernetes/resource.yaml
          


