name: kubernetes-pod

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - "**"


jobs:
  create_pod:
    runs-on: self-hosted

    steps:
      - name: look at the github repo
        uses: actions/checkout@v2

      - name: Set kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" > $HOME/kubeconfig
          echo $HOME/kubeconfig

        shell: bash

      - name: Do some checks
        run: |
             cat c/users/dries/.kube/config
             echo "Check api resource for kubectl"
             kubectl --kubeconfig ~/.kube/config api-resources
             echo "Check versions of kubectl (client)"
             kubectl --kubeconfig ~/.kube/config version --client
             kubectl --kubeconfig ~/.kube/config version

      - name: Create a kubernetes pod
        run: kubectl apply -f ./kubernetes/resource.yaml --validate=false
          


