name: kubernetes-pod

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - "**"


jobs:
  create_pod:
    runs-on: self-hosted

    steps:
      - name: look at the github repo
        uses: actions/checkout@v2

      - name: Do some checks
        run: |
             echo "Check api resource for kubectl"
             kubectl api-resources
             echo "Check versions of kubectl (client)"
             kubectl version --client
             kubectl version

      - name: Create a kubernetes pod
        run: kubectl apply -f ./kubernetes/resource.yaml --validate=false
          


